### ISSUE TITLE
Разное. Продолжение

### ISSUE THREAD

**Issue by kate-fsd** [olegkoryakov/toxin#10]
1. Курсор pointer на checkbox и прочих

**Comment by olegkoryakov** [comment]
Исправил

**Comment by kate-fsd** [comment]
Ты вынес твиттер, фб... лого в отдельные компоненты. А это все таки просто картинки. Сделай их svg и вынеси в папку images туда, где они используются

**Comment by kate-fsd** [comment]
И с кодом svg который у тебя есть в компонентах (например в рейтинге) поступи так же, чтобы он не засорял основной код

**Comment by kate-fsd** [comment]
Картинки положи туда же, где она используется. Например звездочки в папку star-rating/images, так как они используются в компоненте. А вот картинки комнат для карточек room-card на самый верхний уровень, search-room/images

**Comment by kate-fsd** [comment]
Карточка room-details всегда люкс. Сделай чтобы это значение можно было передать в аргументах. 
В search-room люксы не проставлены, похоже поменял название какой-то переменной)

**Comment by kate-fsd** [comment]
> Карточка room-details всегда люкс.

Так ты не сможешь язык поменять
```
      &:before {
        content: 'Люкс';
```

**Comment by kate-fsd** [comment]
в room-comments картинки должны лежать выше, это ж не часть компонента

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/93635239-a1358180-f9fa-11ea-99c7-9d2dfe5905e7.png)

добавь на число неразрывный пробел

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/93899177-b82aeb00-fcfc-11ea-8ec9-2dda6f8d67d0.png)

компонент goods. Первую проверку можно убрать и в следующих убрать else
