### ISSUE TITLE
Pixel perfect

### ISSUE THREAD

**Issue by kate-fsd** [olegkoryakov/toxin#11]
Проверь, есть ли расхождения с макетом
Например здесь
![image](https://user-images.githubusercontent.com/66846004/90429881-28779880-e0cf-11ea-9099-16747770a892.png)
Допускается расхождение в пару пикселей

**Comment by olegkoryakov** [comment]
Исправил.

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/91464926-cae50800-e895-11ea-9a7a-72fa98a62023.png)

![image](https://user-images.githubusercontent.com/66846004/91464963-dafce780-e895-11ea-8169-1295fc6a30d8.png)

![image](https://user-images.githubusercontent.com/66846004/91464990-e6e8a980-e895-11ea-9b8b-f063518162a7.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/91465341-58c0f300-e896-11ea-8475-7a378e51d949.png)

**Comment by kate-fsd** [comment]
Проверь еще эти чекбоксы
![image](https://user-images.githubusercontent.com/66846004/91466596-0b458580-e898-11ea-8df2-801df29ad17f.png)
