### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by kate-fsd** [olegkoryakov/toxin#17]
Тег article используется не по назначению

**Comment by kate-fsd** [comment]
еще есть article

**Comment by kate-fsd** [comment]
Мне кажется section тут тоже не подходит, эти блоки слишком маленькие и не имеют смысловой завершенности

**Comment by rpopov94** [comment]
Возможно данное свойство где то ниже используется

**Comment by kate-fsd** [comment]
До сих пор много section, там где они не нужны. Например section.range-slider
