### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by iatsdotfatr** [olegkoryakov/toxin#3]
![Screenshot from 2020-07-27 20-22-40](https://user-images.githubusercontent.com/51824674/88554364-401bae00-d048-11ea-9f0e-2ff4d3aa692d.png)

Раздел "Пару слов о том, чему научился", наверное, лучше было отправлять по телеге с данными о себе).

**Comment by olegkoryakov** [comment]
Приветствую.
Убрал раздел "Пару слов о том, чему научился" и добавил инфу про развертывание :)
