### ISSUE TITLE
Разное

### ISSUE THREAD

**Issue by iatsdotfatr** [olegkoryakov/toxin#4]
1. Названия шрифтов
![Screenshot from 2020-07-27 20-23-49](https://user-images.githubusercontent.com/51824674/88554617-896bfd80-d048-11ea-9512-133d08ecb350.png)

2. В Calendar.ts поправить linebreak
![Screenshot from 2020-07-27 20-20-40](https://user-images.githubusercontent.com/51824674/88555132-334b8a00-d049-11ea-805e-a2351ee8857d.png)

3. Здесь лучше автоимпорт настроить, например, см. webpack dependency management
![autoimport](https://user-images.githubusercontent.com/51824674/88555234-58d89380-d049-11ea-9ca4-52a866eaf9be.png)

4. Передаваемые объектом параметры деструктурировать
![destucturing](https://user-images.githubusercontent.com/51824674/88555434-a7862d80-d049-11ea-87f1-a6a8273f84a7.png)

**Comment by olegkoryakov** [comment]
1.  Поправил названия шрифтов и картинок.
2. Исправил ошибку, отключением правила linebreak-style в .eslintrc.json.
3. Настроил автоимпорт, накатив "node-sass-glob-importer" для возможности использовать
конструкции типа: ` @import '../blocks/*/*.scss`
4. Деструктировал параметр внутри миксина.

**Comment by iatsdotfatr** [comment]
>     1. Поправил названия шрифтов и картинок.
1. Гит по умолчанию игнорирует смену регистра
![fonts](https://user-images.githubusercontent.com/51824674/89108934-ad6f7a80-d45e-11ea-8f9d-3927b25f85b5.png)

2. Убрать dist в gitignore.
![dist](https://user-images.githubusercontent.com/51824674/89108943-be1ff080-d45e-11ea-8809-25430a46f30f.png)

3. Повтор
![double](https://user-images.githubusercontent.com/51824674/89108962-dbed5580-d45e-11ea-980f-96d0e437d56d.png)

**Comment by olegkoryakov** [comment]
1. есть
2. убрал, закидывал туда дист, потому что не видел другого способа добавить проект на гх пэйджес
3. поправил
