### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by iatsdotfatr** [olegkoryakov/toxin#5]
1. Элементы и т.д. вкладывать в блок через &.
![ampersand](https://user-images.githubusercontent.com/51824674/88555639-de5c4380-d049-11ea-88c5-1baf4ef8d9a8.png)

2. Фиксированную геометрию к блокам не применять.
![fixed width](https://user-images.githubusercontent.com/51824674/88555854-24190c00-d04a-11ea-993e-5c3c7df8ce0f.png)

3. Модификаторы оформлять через _.
![mod style](https://user-images.githubusercontent.com/51824674/88555928-3b57f980-d04a-11ea-9660-7354acef819c.png)

**Comment by olegkoryakov** [comment]
Исправил.
Похоже я теперь навсегда запомнил, что нельзя вешать геометрию блокам и как правильно называть классы).

**Comment by iatsdotfatr** [comment]
В таких случаях использовать модификатор типа "ключ-значение".
![key-value](https://user-images.githubusercontent.com/51824674/89108999-2a025900-d45f-11ea-9210-1942a4e630b1.png)

**Comment by olegkoryakov** [comment]
Заменил модификатор filled-wide на submit, для остальных не придумал ничего лучше, чем было, так как, на мой взгляд, остальные кнопки в проекте различаются не по логике, а по визуализации.
