### ISSUE TITLE
Стандарты

### ISSUE THREAD

**Issue by iatsdotfatr** [olegkoryakov/toxin#6]

**Comment by iatsdotfatr** [comment]
1. 
![lightweight](https://user-images.githubusercontent.com/51824674/89109012-4900eb00-d45f-11ea-9015-c7140dd014b2.png)
![lightweight2](https://user-images.githubusercontent.com/51824674/89109013-4a321800-d45f-11ea-9dde-1b217c52a8bf.png)

2. 
![link](https://user-images.githubusercontent.com/51824674/89109019-561dda00-d45f-11ea-8d57-e78151fe0e0d.png)
![link2](https://user-images.githubusercontent.com/51824674/89109021-574f0700-d45f-11ea-931d-6e8eab00ca7e.png)

3. Миксы не использовать, для позиционирования блока создавать элемент-обертку, для изменения внутренних стилей использовать модификаторы.
![mix](https://user-images.githubusercontent.com/51824674/89109072-c6c4f680-d45f-11ea-928c-1559f9e72218.png)

4. Комментарии убрать
![remove comments](https://user-images.githubusercontent.com/51824674/89109083-e0fed480-d45f-11ea-82be-b39ea9d99384.png)

5. Фиксированную высоту использовать только там, где необходимо
![fixed height](https://user-images.githubusercontent.com/51824674/89109110-215e5280-d460-11ea-8f23-097d4e80f987.png)
.

**Comment by olegkoryakov** [comment]
Исправил
