### ISSUE TITLE
Функционал

### ISSUE THREAD

**Issue by kate-fsd** [olegkoryakov/toxin#8]
1. В календаре сделай так, чтобы при нажатии на применить он закрывался, а при нажатии на очистить - кругляши  исчезали.

2. Прыгают кнопки. Нужно чтобы при нажатии на кнопку +/- сразу подставлялся текст. Если 0, не добавляй в строку (так "1 гость, 0 младенцев"), а если все значения по нулям, вместо "0 гостей, 0 младенцев" лучше подставить "Сколько гостей".
С кнопками применить и очистить - по аналогии с календарем.
![Peek 2020-08-17 20-36](https://user-images.githubusercontent.com/66846004/90426317-8f924e80-e0c9-11ea-8af9-90f7524f3ab5.gif)

3. Сделай так, чтобы при клике вне дропдаунов (календарей, гостей..), они закрывались

4. При наведении секции должны расширяться а число внутри пончика меняться
![image](https://user-images.githubusercontent.com/66846004/90427441-362b1f00-e0cb-11ea-98f6-1b010385b9fc.png)

5. В карточки комнат добавь слайдер

6. filter-date-dropdown - формат даты не совпадает с макетом

7. Если слайдер твой, можешь пока не исправлять, оставить на потом) А можешь заменить на готовый
![Peek 2020-08-17 20-56](https://user-images.githubusercontent.com/66846004/90428106-295afb00-e0cc-11ea-9f37-9a0269927d3a.gif)

8. В некоторых местах нужно убрать возможность вводить что то в поля
![image](https://user-images.githubusercontent.com/66846004/90429068-acc91c00-e0cd-11ea-95de-525a028665f0.png)

9. Здесь должна быть маска
![image](https://user-images.githubusercontent.com/66846004/90429374-4690c900-e0ce-11ea-8be3-32e3969297ec.png)

**Comment by olegkoryakov** [comment]
Исправил

**Comment by kate-fsd** [comment]
В карточках комнат смена картинки при клике по кругляшкам не работает
![image](https://user-images.githubusercontent.com/66846004/91900129-e0e43580-eca6-11ea-824a-dd503d219daa.png)

**Comment by kate-fsd** [comment]
> 2\. Нужно чтобы при нажатии на кнопку +/- сразу подставлялся текст.

не работает
