### ISSUE TITLE
Внешний вид

### ISSUE THREAD

**Issue by kate-fsd** [olegkoryakov/toxin#9]
1. У календаря есть уголочки и у него не должно быть тени. 
![image](https://user-images.githubusercontent.com/66846004/90425635-c025b880-e0c8-11ea-82c8-70a8174138e0.png)
ГГГГ должно быть

2. Кнопка с сердечком - число не выровнено

3. Страница room details - над футером слишком яркая тень

4. Dropdown - навожу на поле - рамочка яркая. Навожу на стрелочку внутри - рамка неяркая. То же в subscription

**Comment by olegkoryakov** [comment]
Исправил

**Comment by kate-fsd** [comment]
Не по центру по вертикали и по горизонтали
![image](https://user-images.githubusercontent.com/66846004/91901388-d3c84600-eca8-11ea-8efd-d74cdcae31d1.png) 
![image](https://user-images.githubusercontent.com/66846004/91901487-f5293200-eca8-11ea-95cd-225d9343d83b.png)

**Comment by kate-fsd** [comment]
dropdown бледнее чем в макете, и на нем стоит текстовый курсор, как будто это инпут. Лучше сделать курсор default

**Comment by kate-fsd** [comment]
Пончик в соответствие с макетом
![image](https://user-images.githubusercontent.com/66846004/93446703-2f661680-f8da-11ea-8973-303c94bdcb76.png)

**Comment by kate-fsd** [comment]
Страница room-details. Заголовки Сведения о номере, Впечатления от номера, Отзывы посетителей номера, Правила  - все выровнены по левому краю и у всех разный отступ от края. Или на маленьких размерах выравнивай по центру или сделай им одинаковый отступ

**Comment by kate-fsd** [comment]
room-details вертикальные отступы на мобильных слишком отличаются
![image](https://user-images.githubusercontent.com/66846004/93635124-70554c80-f9fa-11ea-963d-501802a58428.png)
![image](https://user-images.githubusercontent.com/66846004/93635146-7d723b80-f9fa-11ea-85fb-5f5e7cfcc7bb.png)
